
name: Disney CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9' 

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: disney-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Zip IPA
        run: |-
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: disney-ipa
          path: build/ios/iphoneos/Runner.app.zip

  create_release:
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: disney-apk

      - name: Download IPA from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: disney-ipa

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.apk
          asset_name: disney.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Runner.app.zip
          asset_name: disney.ipa
          asset_content_type: application/zip
